export interface OdooProduct {
  id: number;
  display_name: string;
  activity_ids: number[];
  activity_state: boolean | string;
  activity_user_id: boolean | number;
  activity_type_id: boolean | number;
  activity_type_icon: boolean | string;
  activity_date_deadline: boolean | string;
  my_activity_date_deadline: boolean | string;
  activity_summary: boolean | string;
  activity_exception_decoration: boolean | string;
  activity_exception_icon: boolean | string;
  activity_calendar_event_id: boolean | number;
  message_is_follower: boolean;
  message_follower_ids: number[];
  message_partner_ids: number[];
  message_ids: number[];
  has_message: boolean;
  message_needaction: boolean;
  message_needaction_counter: number;
  message_has_error: boolean;
  message_has_error_counter: number;
  message_attachment_count: number;
  rating_ids: number[];
  website_message_ids: number[];
  message_has_sms_error: boolean;
  price_extra: number;
  lst_price: number;
  default_code: string;
  code: string;
  partner_ref: string;
  active: boolean;
  product_tmpl_id: [number, string]; // [id, name]
  barcode: boolean | string;
  product_uom_ids: number[];
  product_template_attribute_value_ids: number[];
  product_template_variant_value_ids: number[];
  combination_indices: string;
  is_product_variant: boolean;
  standard_price: number;
  volume: number;
  weight: number;
  pricelist_rule_ids: number[];
  product_document_ids: number[];
  product_document_count: number;
  additional_product_tag_ids: number[];
  all_product_tag_ids: number[];
  image_variant_1920: string | boolean;
  image_variant_1024: string | boolean;
  image_variant_512: string | boolean;
  image_variant_256: string | boolean;
  image_variant_128: string | boolean;
  can_image_variant_1024_be_zoomed: boolean;
  image_1920: string | boolean; // Base64 string
  image_1024: string | boolean;
  image_512: string | boolean;
  image_256: string | boolean;
  image_128: string | boolean;
  can_image_1024_be_zoomed: boolean;
  write_date: string;
  is_favorite: boolean;
  is_in_selected_section_of_order: boolean;
  create_uid: [number, string];
  create_date: string;
  write_uid: [number, string];
  is_image_fetch_pending: boolean;
  tax_string: string;
  stock_quant_ids: number[];
  stock_move_ids: number[];
  qty_available: number;
  virtual_available: number;
  free_qty: number;
  incoming_qty: number;
  outgoing_qty: number;
  orderpoint_ids: number[];
  nbr_moves_in: number;
  nbr_moves_out: number;
  nbr_reordering_rules: number;
  reordering_min_qty: number;
  reordering_max_qty: number;
  putaway_rule_ids: number[];
  storage_category_capacity_ids: number[];
  show_on_hand_qty_status_button: boolean;
  show_forecasted_qty_status_button: boolean;
  show_qty_update_button: boolean;
  valid_ean: boolean;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  lot_properties_definition: any[];
  purchased_product_qty: number;
  is_in_purchase_order: boolean;
  avg_cost: number;
  total_value: number;
  company_currency_id: [number, string];
  has_image: boolean;
  purchase_order_line_ids: number[];
  monthly_demand: number;
  suggested_qty: number;
  suggest_estimated_price: number;
  sales_count: number;
  product_catalog_product_is_in_sale_order: boolean;
  name: string;
  sequence: number;
  description: boolean | string;
  description_purchase: boolean | string;
  description_sale: boolean | string;
  type: string;
  combo_ids: number[];
  service_tracking: string;
  categ_id: [number, string];
  currency_id: [number, string];
  cost_currency_id: [number, string];
  list_price: number;
  volume_uom_name: string;
  weight_uom_name: string;
  sale_ok: boolean;
  purchase_ok: boolean;
  uom_id: [number, string];
  uom_ids: number[];
  uom_name: string;
  company_id: boolean | number;
  seller_ids: number[];
  variant_seller_ids: number[];
  color: number;
  attribute_line_ids: number[];
  valid_product_template_attribute_line_ids: number[];
  product_variant_ids: number[];
  product_variant_id: [number, string];
  product_variant_count: number;
  has_configurable_attributes: boolean;
  is_dynamically_created: boolean;
  product_tooltip: string;
  product_tag_ids: number[];
  product_properties: any[];
  taxes_id: number[];
  supplier_taxes_id: number[];
  property_account_income_id: boolean | number;
  property_account_expense_id: boolean | number;
  account_tag_ids: number[];
  fiscal_country_codes: string;
  is_storable: boolean;
  responsible_id: [number, string];
  property_stock_production: [number, string];
  property_stock_inventory: [number, string];
  sale_delay: number;
  tracking: string;
  lot_sequence_id: [number, string];
  serial_prefix_format: string;
  next_serial: string;
  description_picking: boolean | string;
  description_pickingout: boolean | string;
  description_pickingin: boolean | string;
  location_id: boolean | number;
  warehouse_id: boolean | number;
  has_available_route_ids: boolean;
  route_ids: number[];
  route_from_categ_ids: number[];
  unspsc_code_id: boolean | number;
  purchase_method: string;
  purchase_line_warn_msg: boolean | string;
  cost_method: string;
  valuation: string;
  lot_valuated: boolean;
  property_price_difference_account_id: boolean | number;
  available_in_pos: boolean;
  to_weight: boolean;
  pos_categ_ids: number[];
  public_description: boolean | string;
  pos_optional_product_ids: number[];
  pos_sequence: number;
  service_type: string;
  sale_line_warn_msg: boolean | string;
  expense_policy: string;
  visible_expense_policy: boolean;
  invoice_policy: string;
  optional_product_ids: number[];
  service_to_purchase: boolean;
  l10n_co_edi_brand: string;
  l10n_co_edi_customs_code: boolean | string;
  l10n_co_edi_ref_nominal_tax: number;
  planning_enabled: boolean;
  planning_role_id: boolean | number;
  project_id: boolean | number;
  project_template_id: boolean | number;
  task_template_id: boolean | number;
  service_policy: string;
  l10n_co_dian_mandate_contract: boolean | string;
}
